# Generated by Django 2.0 on 2018-08-23 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mailing_address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('shirt', models.CharField(blank=True, choices=[('XS', 'X Small'), ('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large'), ('XL', 'X Large'), ('2X', '2X Large'), ('3X', '3X Large'), ('4X', '4X Large'), ('5X', '5X Large')], default='XL', max_length=2)),
                ('twitter', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('twitch', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('events', models.ManyToManyField(to='mainApp.Events')),
            ],
            options={
                'ordering': ('influencer_name',),
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='influencer',
            name='tags',
            field=models.ManyToManyField(to='mainApp.Tags'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
