# Generated by Django 2.0 on 2018-08-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ('event_name',)},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ('tag_name',)},
        ),
        migrations.AddField(
            model_name='influencer',
            name='country',
            field=models.CharField(default='US', max_length=20),
        ),
    ]
